// packages/website/src/pages/documentation/Header.tsx
import { Fragment } from "react";
import { Popover, Transition } from "@headlessui/react";
import {
	ArrowPathIcon,
	Bars3Icon,
	ChartBarIcon,
	CursorArrowRaysIcon,
	DocumentChartBarIcon,
	ShieldCheckIcon,
	Squares2X2Icon,
	XMarkIcon,
} from "@heroicons/react/24/outline";
import { ChevronDownIcon } from "@heroicons/react/20/solid";

const solutions = [
	{
		name: "Analytics",
		description:
			"Get a better understanding of where your traffic is coming from.",
		href: "#",
		icon: ChartBarIcon,
	},
	{
		name: "Engagement",
		description: "Speak directly to your customers in a more meaningful way.",
		href: "#",
		icon: CursorArrowRaysIcon,
	},
	{
		name: "Security",
		description: "Your customers' data will be safe and secure.",
		href: "#",
		icon: ShieldCheckIcon,
	},
	{
		name: "Integrations",
		description: "Connect with third-party tools that you're already using.",
		href: "#",
		icon: Squares2X2Icon,
	},
	{
		name: "Automations",
		description:
			"Build strategic funnels that will drive your customers to convert",
		href: "#",
		icon: ArrowPathIcon,
	},
	{
		name: "Reports",
		description:
			"Get detailed reports that will help you make more informed decisions ",
		href: "#",
		icon: DocumentChartBarIcon,
	},
];
const resources = [
	{
		name: "Help Center",
		description:
			"Get all of your questions answered in our forums or contact support.",
		href: "#",
	},
	{
		name: "Guides",
		description:
			"Learn how to maximize our platform to get the most out of it.",
		href: "#",
	},
	{
		name: "Events",
		description:
			"See what meet-ups and other events we might be planning near you.",
		href: "#",
	},
	{
		name: "Security",
		description: "Understand how we take your privacy seriously.",
		href: "#",
	},
];

function classNames(...classes) {
	return classes.filter(Boolean).join(" ");
}

export function Header() {
	return (
		<Popover className="relative bg-white">
			<div className="flex items-center justify-between px-4 py-6 sm:px-6 md:justify-start md:space-x-10">
				<div>
					<a href="#" className="flex">
						<span className="sr-only">Your Company</span>
						<img src="./logo.svg" alt="" />
					</a>
				</div>
				<div className="-my-2 -mr-2 md:hidden">
					<Popover.Button className="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
						<span className="sr-only">Open menu</span>
						<Bars3Icon className="h-6 w-6" aria-hidden="true" />
					</Popover.Button>
				</div>
				<div className="hidden md:flex md:flex-1 md:items-center md:justify-between">
					<Popover.Group as="nav" className="flex space-x-10">
						<Popover className="relative">
							{({ open }) => (
								<>
									<Popover.Button
										className={classNames(
											open ? "text-gray-900" : "text-gray-500",
											"group inline-flex items-center rounded-md bg-white text-base font-medium hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
										)}
									>
										<span>Solutions</span>
										<ChevronDownIcon
											className={classNames(
												open ? "text-gray-600" : "text-gray-400",
												"ml-2 h-5 w-5 group-hover:text-gray-500"
											)}
											aria-hidden="true"
										/>
									</Popover.Button>

									<Transition
										as={Fragment}
										enter="transition ease-out duration-200"
										enterFrom="opacity-0 translate-y-1"
										enterTo="opacity-100 translate-y-0"
										leave="transition ease-in duration-150"
										leaveFrom="opacity-100 translate-y-0"
										leaveTo="opacity-0 translate-y-1"
									>
										<Popover.Panel className="absolute z-10 -ml-4 mt-3 w-screen max-w-md transform lg:max-w-3xl">
											<div className="overflow-hidden rounded-lg shadow-lg ring-1 ring-black ring-opacity-5">
												<div className="relative grid gap-6 bg-white px-5 py-6 sm:gap-8 sm:p-8 lg:grid-cols-2">
													{solutions.map((item) => (
														<a
															key={item.name}
															href={item.href}
															className="-m-3 flex items-start rounded-lg p-3 hover:bg-gray-50"
														>
															<div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-md bg-indigo-500 text-white sm:h-12 sm:w-12">
																<item.icon
																	className="h-6 w-6"
																	aria-hidden="true"
																/>
															</div>
															<div className="ml-4">
																<p className="text-base font-medium text-gray-900">
																	{item.name}
																</p>
																<p className="mt-1 text-sm text-gray-500">
																	{item.description}
																</p>
															</div>
														</a>
													))}
												</div>
												<div className="bg-gray-50 p-5 sm:p-8">
													<a
														href="#"
														className="-m-3 flow-root rounded-md p-3 hover:bg-gray-100"
													>
														<div className="flex items-center">
															<div className="text-base font-medium text-gray-900">
																Enterprise
															</div>
															<span className="ml-3 inline-flex items-center rounded-full bg-indigo-100 px-3 py-0.5 text-xs font-medium leading-5 text-indigo-800">
																New
															</span>
														</div>
														<p className="mt-1 text-sm text-gray-500">
															Empower your entire team with even more advanced
															tools.
														</p>
													</a>
												</div>
											</div>
										</Popover.Panel>
									</Transition>
								</>
							)}
						</Popover>
						<a
							href="#"
							className="text-base font-medium text-gray-500 hover:text-gray-900"
						>
							Pricing
						</a>
						<a
							href="#"
							className="text-base font-medium text-gray-500 hover:text-gray-900"
						>
							Docs
						</a>

						<Popover className="relative">
							{({ open }) => (
								<>
									<Popover.Button
										className={classNames(
											open ? "text-gray-900" : "text-gray-500",
											"group inline-flex items-center rounded-md bg-white text-base font-medium hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
										)}
									>
										<span>More</span>
										<ChevronDownIcon
											className={classNames(
												open ? "text-gray-600" : "text-gray-400",
												"ml-2 h-5 w-5 group-hover:text-gray-500"
											)}
											aria-hidden="true"
										/>
									</Popover.Button>

									<Transition
										as={Fragment}
										enter="transition ease-out duration-200"
										enterFrom="opacity-0 translate-y-1"
										enterTo="opacity-100 translate-y-0"
										leave="transition ease-in duration-150"
										leaveFrom="opacity-100 translate-y-0"
										leaveTo="opacity-0 translate-y-1"
									>
										<Popover.Panel className="absolute left-1/2 z-10 mt-3 w-screen max-w-xs -translate-x-1/2 transform px-2 sm:px-0">
											<div className="overflow-hidden rounded-lg shadow-lg ring-1 ring-black ring-opacity-5">
												<div className="relative grid gap-6 bg-white px-5 py-6 sm:gap-8 sm:p-8">
													{resources.map((item) => (
														<a
															key={item.name}
															href={item.href}
															className="-m-3 block rounded-md p-3 hover:bg-gray-50"
														>
															<p className="text-base font-medium text-gray-900">
																{item.name}
															</p>
															<p className="mt-1 text-sm text-gray-500">
																{item.description}
															</p>
														</a>
													))}
												</div>
											</div>
										</Popover.Panel>
									</Transition>
								</>
							)}
						</Popover>
					</Popover.Group>
					<div className="flex items-center md:ml-12">
						<a
							href="#"
							className="text-base font-medium text-gray-500 hover:text-gray-900"
						>
							Sign in
						</a>
						<a
							href="#"
							className="ml-8 inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700"
						>
							Sign up
						</a>
					</div>
				</div>
			</div>

			<Transition
				as={Fragment}
				enter="duration-200 ease-out"
				enterFrom="opacity-0 scale-95"
				enterTo="opacity-100 scale-100"
				leave="duration-100 ease-in"
				leaveFrom="opacity-100 scale-100"
				leaveTo="opacity-0 scale-95"
			>
				<Popover.Panel
					focus
					className="absolute inset-x-0 top-0 origin-top-right transform p-2 transition md:hidden"
				>
					<div className="divide-y-2 divide-gray-50 rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
						<div className="px-5 pt-5 pb-6">
							<div className="flex items-center justify-between">
								<div>
									<img
										className="h-8 w-auto"
										src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
										alt="Your Company"
									/>
								</div>
								<div className="-mr-2">
									<Popover.Button className="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
										<span className="sr-only">Close menu</span>
										<XMarkIcon className="h-6 w-6" aria-hidden="true" />
									</Popover.Button>
								</div>
							</div>
							<div className="mt-6">
								<nav className="grid gap-6">
									{solutions.map((item) => (
										<a
											key={item.name}
											href={item.href}
											className="-m-3 flex items-center rounded-lg p-3 hover:bg-gray-50"
										>
											<div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-md bg-indigo-500 text-white">
												<item.icon className="h-6 w-6" aria-hidden="true" />
											</div>
											<div className="ml-4 text-base font-medium text-gray-900">
												{item.name}
											</div>
										</a>
									))}
								</nav>
							</div>
						</div>
						<div className="py-6 px-5">
							<div className="grid grid-cols-2 gap-4">
								<a
									href="#"
									className="text-base font-medium text-gray-900 hover:text-gray-700"
								>
									Pricing
								</a>

								<a
									href="#"
									className="text-base font-medium text-gray-900 hover:text-gray-700"
								>
									Docs
								</a>

								<a
									href="#"
									className="text-base font-medium text-gray-900 hover:text-gray-700"
								>
									Enterprise
								</a>
								{resources.map((item) => (
									<a
										key={item.name}
										href={item.href}
										className="text-base font-medium text-gray-900 hover:text-gray-700"
									>
										{item.name}
									</a>
								))}
							</div>
							<div className="mt-6">
								<a
									href="#"
									className="flex w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700"
								>
									Sign up
								</a>
								<p className="mt-6 text-center text-base font-medium text-gray-500">
									Existing customer?{" "}
									<a href="#" className="text-indigo-600 hover:text-indigo-500">
										Sign in
									</a>
								</p>
							</div>
						</div>
					</div>
				</Popover.Panel>
			</Transition>
		</Popover>
	);
}

// source-code/website/src/pages/documentation/Header.tsx
import { createSignal, For } from "solid-js";

const links = [
	{ name: "Docs", href: "/documantaion" },
	{ name: "Docs", href: "/documantaion" },
];

export function Header() {
	return (
		<div class="relative bg-white">
			<div
				class="pointer-events-none absolute inset-0 z-30 "
				aria-hidden="true"
			></div>
			<div class="relative z-20">
				<div class="mx-auto flex  items-center justify-between px-4 py-5 sm:px-6 sm:py-4 md:justify-start md:space-x-10 lg:px-8">
					<div class="h-8 w-auto sm:h-10">
						<a href="#" class="flex">
							<span class="sr-only">Inlang</span>
							<img class="h-8 w-auto sm:h-10" src="logo.svg" alt="" />
						</a>
					</div>
					{/* Responsive icon start */}
					<div class="-my-2 -mr-2 md:hidden">
						<button
							type="button"
							class="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
							aria-expanded="false"
						>
							<span class="sr-only">Open menu</span>
							<svg
								class="h-6 w-6"
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								stroke-width="1.5"
								stroke="currentColor"
								aria-hidden="true"
							>
								<path
									stroke-linecap="round"
									stroke-linejoin="round"
									d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
								/>
							</svg>
						</button>
					</div>
					{/*Responsive icon end  */}
					<div class="hidden md:flex md:flex-1 md:items-center md:justify-between">
						<nav class="flex space-x-10">
							<For each={links}>
								{(link) => (
									<a class="link-primary" target="_blank" href={link.href}>
										{link.name}
									</a>
								)}
							</For>
						</nav>
						<div class="flex items-center md:ml-12">
							<a
								href="#"
								class="text-base font-medium text-gray-500 hover:text-gray-900"
							>
								Sign in
							</a>
							<a
								href="#"
								class="ml-8 inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700"
							>
								Sign up
							</a>
						</div>
					</div>
				</div>
			</div>

			{/* <!--
    Mobile menu, show/hide based on mobile menu state.

    Entering: "duration-200 ease-out"
      From: "opacity-0 scale-95"
      To: "opacity-100 scale-100"
    Leaving: "duration-100 ease-in"
      From: "opacity-100 scale-100"
      To: "opacity-0 scale-95"
  --> */}
			<div class="absolute inset-x-0 top-0 z-30 origin-top-right transform p-2 transition md:hidden">
				<div class="divide-y-2 divide-gray-50 rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
					<div class="px-5 pt-5 pb-6 sm:pb-8">
						<div class="flex items-center justify-between">
							<div>
								<img
									class="h-8 w-auto"
									src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
									alt="Your Company"
								/>
							</div>
							<div class="-mr-2">
								<button
									type="button"
									class="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
								>
									<span class="sr-only">Close menu</span>
									{/* <!-- Heroicon name: outline/x-mark --> */}
									<svg
										class="h-6 w-6"
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke-width="1.5"
										stroke="currentColor"
										aria-hidden="true"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											d="M6 18L18 6M6 6l12 12"
										/>
									</svg>
								</button>
							</div>
						</div>
						{/* Nav, responsive */}
					</div>
					<div class="py-6 px-5">
						<div class="grid grid-cols-2 gap-4">
							<a
								href="#"
								class="rounded-md text-base font-medium text-gray-900 hover:text-gray-700"
							>
								Pricing
							</a>
							<a
								href="#"
								class="rounded-md text-base font-medium text-gray-900 hover:text-gray-700"
							>
								Docs
							</a>
						</div>
						<div class="mt-6">
							<a
								href="#"
								class="flex w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700"
							>
								Sign up
							</a>
							<p class="mt-6 text-center text-base font-medium text-gray-500">
								Existing customer?
								<a href="#" class="text-indigo-600 hover:text-indigo-500">
									Sign in
								</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}
