// apps/editor-solidjs/pages/git/Layout.tsx
import { For, JSXElement } from "solid-js";
import { searchParameters } from "./state";

export function Layout(props: { children: JSXElement }) {
  return (
    <>
      <Breadcrumbs></Breadcrumbs>
      {props.children}
    </>
  );
}

function Breadcrumbs() {
  // ugly stitching together of paths
  // let breadcrumbs: () => { name: string; href: string; isCurrentPage: boolean }[];
  function breadcrumbs() {
    // consists of last two paths (/) of the uri (skipping https:// etc.)
    const respositoryName = window.location.pathname
      .split("/")
      .slice(-2)
      .join(" ");
    if (searchParameters.dir === "/") {
      return [
        {
          name: respositoryName,
          href: `${window.location.pathname}`,
          isCurrentPage: true,
        },
      ];
    }
    const result = [
      {
        name: respositoryName,
        href: `${window.location.pathname}`,
        isCurrentPage: false,
      },
    ];
    for (const [i, subpath] of searchParameters.dir
      .split("/")
      .slice(1, -1)
      .entries()) {
      // the path(s) "above" the subpath
      // .slice(1) to remove prefixed slash as in the each loop above
      const rootpath = searchParameters.dir
        .split("/")
        .slice(1)
        .slice(0, i)
        .join("/");
      //  if roothpath exists ? merge paths : else only take subpath
      const dir = rootpath ? `/${rootpath}/${subpath}/` : `/${subpath}/`;
      // ugly slicing of slashes
      let isCurrentPage =
        searchParameters.dir.slice(
          searchParameters.dir.slice(0, -1).lastIndexOf("/") + 1,
          -1
        ) === subpath;
      result.push({
        name: subpath,
        href: `/git/${window.location.pathname}?dir=${dir}`,
        isCurrentPage,
      });
    }
    return result;
  }

  return (
    <div class="border px-4 py-2 rounded">
      <sl-breadcrumb>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          class="w-6 h-6 pr-2"
        >
          <path
            fill-rule="evenodd"
            d="M3 2.75A2.75 2.75 0 015.75 0h14.5a.75.75 0 01.75.75v20.5a.75.75 0 01-.75.75h-6a.75.75 0 010-1.5h5.25v-4H6A1.5 1.5 0 004.5 18v.75c0 .716.43 1.334 1.05 1.605a.75.75 0 01-.6 1.374A3.25 3.25 0 013 18.75v-16zM19.5 1.5V15H6c-.546 0-1.059.146-1.5.401V2.75c0-.69.56-1.25 1.25-1.25H19.5z"
          />
          <path d="M7 18.25a.25.25 0 01.25-.25h5a.25.25 0 01.25.25v5.01a.25.25 0 01-.397.201l-2.206-1.604a.25.25 0 00-.294 0L7.397 23.46a.25.25 0 01-.397-.2v-5.01z" />
        </svg>
        <For each={breadcrumbs()}>
          {(breadcrumb) => (
            <sl-breadcrumb-item prop:href={breadcrumb.href}>
              {breadcrumb.name}
            </sl-breadcrumb-item>
          )}
        </For>
      </sl-breadcrumb>
    </div>
  );
}

// apps/dashboard/src/routes/uri/[...uri]/__layout.svelte
<script lang="ts">
	import InlineLoadingWrapper from '$lib/components/InlineLoadingWrapper.svelte';
	import { t } from '$lib/services/i18n';
	import http from 'isomorphic-git/http/web';
	import { fs } from '$lib/stores/filesystem';
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { Breadcrumb, BreadcrumbItem } from 'carbon-components-svelte';
	import { searchParams } from '$lib/stores/routes/uriStores';
	import GitStatus from '$lib/components/GitStatus.svelte';
	import { clone } from '$lib/services/git/index';

	let inlineLoadingStatus: InlineLoadingWrapper['$$prop_def']['status'] = 'inactive';

	let isLoading = true;

	async function cloneRepository(): Promise<void> {
		inlineLoadingStatus = 'active';
		const result = await clone({
			fs: fs.callbackBased,
			dir: '/',
			http,
			url: $page.params.uri,
			corsProxy: 'https://cors.isomorphic-git.org'
		});
		if (result.isErr) {
			inlineLoadingStatus = 'error';
			alert(result.error);
		} else {
			inlineLoadingStatus = 'finished';
		}
		fs.refresh();
	}

	onMount(async () => {
		await cloneRepository();
		isLoading = false;
	});
</script>

<Breadcrumb class="mb-1">
	<BreadcrumbItem href="/uri/{$page.params.uri}" isCurrentPage={$searchParams.dir === '/'}>
		<h2>
			<!-- the title. consisting of the last two paths (/) of the uri -->
			{$page.params.uri.split('/').slice(-2).join('/')}
		</h2>
	</BreadcrumbItem>
	<!-- slice = skip slashes when splitting path -->
	{#each $searchParams.dir.split('/').slice(1, -1) as subpath, i}
		<!-- 
			rootpath = the path(s) "above" the subpath
			.slice(1) to remove prefixed slash as in the each loop above
		-->
		{@const rootpath = $searchParams.dir.split('/').slice(1).slice(0, i).join('/')}
		<!-- dir = if roothpath exists ? merge paths : else only take subpath -->
		{@const dir = rootpath ? `/${rootpath}/${subpath}/` : `/${subpath}/`}
		<!-- isCurrentPage = ugly slicing of slashes -->
		<BreadcrumbItem
			href="/uri/{$page.params.uri}?dir={dir}"
			isCurrentPage={$searchParams.dir.slice(
				$searchParams.dir.slice(0, -1).lastIndexOf('/') + 1,
				-1
			) === subpath}
		>
			<h2>
				{subpath}
			</h2>
		</BreadcrumbItem>
	{/each}
</Breadcrumb>
<br />

{#if isLoading}
	<InlineLoadingWrapper
		status={inlineLoadingStatus}
		activeDescription={$t('working-on-it')}
		finishedDescription={$t('generic.success')}
	/>
{:else}
	<GitStatus />
	<slot />
{/if}
