// inlang/source-code/paraglide/paraglide-js-adapter-sveltekit/example/src/routes/[lang]/+page.svelte
<script lang="ts">
  import { setLanguageTag, languageTag } from "../../paraglide/runtime";
  import * as m from "../../paraglide/messages"
</script>
  
<p>{m.greeting({ name: "Samuel", count: 5 })}</p>
<p>{m.currentLanguageTag({ languageTag: languageTag() })}</p>
<button on:click={() => setLanguageTag("de")}>change language to "de"</button>
<button on:click={() => setLanguageTag("en")}>change language to "en"</button>

// packages/paraglide/paraglide-js-adapter-next/example-app/src/app/[lang]/page.tsx
import * as m from "@/paraglide/messages.js"
import { languageTag } from "@/paraglide/runtime.js"

export default function Home() {
	return (
		<main>
			<p>{m.greeting({ name: "Samuel", count: 5 })}</p>
			<p>{m.currentLanguageTag({ languageTag: languageTag() })}</p>

			<a href="/de">
				<button>change language to "de"</button>
			</a>
			<a href="/en">
				<button>change language to "en"</button>
			</a>
		</main>
	)
}
