// packages/paraglide/paraglide-js-adapter-next/examples/app/src/app/about/page.tsx
import * as m from "@/paraglide/messages.js"
export default function About() {
	return (
		<>
			<main>
				<h1>{m.about()}</h1>

				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt
					ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
					ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
					reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
					sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
					est laborum.
				</p>
			</main>
		</>
	)
}

// inlang/source-code/paraglide/paraglide-js-adapter-sveltekit/example/src/routes/about/+page.svelte
<script>
    import * as m from "$paraglide/messages.js"
</script>

<h1>{m.about()}</h1>


<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod tempor 
    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
    nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore 
    eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt 
    in culpa qui officia deserunt mollit anim id est laborum.
</p>
