// packages/paraglide/paraglide-js-adapter-sveltekit/example/src/lib/Header.svelte
<!--
    @component
    Adds alternate links to the head of the page for each available language. 
    This is vital for SEO.
-->
<script lang="ts">
	import { page } from "$app/stores"
	import { availableLanguageTags, sourceLanguageTag } from "$paraglide/runtime"
	import { translatePath } from "./i18n"
</script>

<svelte:head>
	{#each availableLanguageTags as lang}
		<link rel="alternate" hreflang={lang} href={translatePath($page.url.pathname, lang)} />
	{/each}
</svelte:head>


<style>
	/* Optional styling */
	:host {
		display: block;
	}
</style>

// packages/paraglide/paraglide-js-adapter-next/src/Header.tsx
"use client"
import {
	availableLanguageTags,
	sourceLanguageTag,
} from "$paraglide-adapter-next-internal/runtime.js"
import Head from "next/head"
import { useRouter } from "next/router"
import React from "react"

/**
 * Adds alternate links for all available languages to the head.
 */
export default function Header(): React.ReactNode {
	const { asPath } = useRouter()

	function getTranslatedPath(languageTag: string) {
		if (languageTag === sourceLanguageTag) return asPath
		return `/${languageTag}${asPath}`
	}

	return (
		<Head>
			{availableLanguageTags.map((lang) => (
				<link rel="alternate" hrefLang={lang} href={getTranslatedPath(lang)} key={lang} />
			))}
		</Head>
	)
}
