// inlang/source-code/paraglide/paraglide-js-react/example/src/App.jsx
import * as m from "@inlang/paraglide-js/messages"
import { setLanguageTag, languageTag } from "@inlang/paraglide-js"

function App() {
	console.log("rendering app")
	return (
		<>
			<p>{m.greeting({ name: "Samuel", count: 5 })}</p>
			<p>{m.currentLanguageTag({ languageTag })}</p>
			<button onClick={() => setLanguageTag("de")}>change language to "de"</button>
			<button onClick={() => setLanguageTag("en")}>change language to "en"</button>
		</>
	)
}

export default App

// packages/paraglide/paraglide-js-adapter-svelte/example/src/App.svelte
<script>
  import { setLanguageTag, languageTag } from '@inlang/paraglide-js/svelte-example';
  import * as m from "@inlang/paraglide-js/svelte-example/messages"
	import ParaglideSvelte from './ParaglideJsProvider.svelte'
</script>

<ParaglideSvelte>

  <p>{m.greeting({ name: "Samuel", count: 5 })}</p>
  <p>{m.currentLanguageTag({languageTag})}</p>
  <button on:click={() => setLanguageTag("de")}>change language to "de"</button>
  <button on:click={() => setLanguageTag("en")}>change language to "en"</button>

</ParaglideSvelte>
