// inlang/source-code/paraglide/paraglide-js-next/example/src/app/[lang]/page.tsx
import * as m from "@inlang/paraglide-js/messages"
import { languageTag } from "@inlang/paraglide-js"

export default function Home() {
	return (
		<main>
			<p>{m.greeting({ name: "Samuel", count: 5 })}</p>
			<p>{m.currentLanguageTag({ languageTag })}</p>
			<a href="/de">
				<button>change language to "de"</button>
			</a>
			<a href="/en">
				<button>change language to "en"</button>
			</a>
		</main>
	)
}

// inlang/source-code/paraglide/paraglide-js-sveltekit/example/src/routes/[lang]/+page.svelte
<script lang="ts">
  import { setLanguageTag, languageTag } from '@inlang/paraglide-js';
  import * as m from "@inlang/paraglide-js/messages"
</script>
  
<p>{m.greeting({ name: "Samuel", count: 5 })}</p>
<p>{m.currentLanguageTag({ languageTag: languageTag() })}</p>
<button on:click={() => setLanguageTag("de")}>change language to "de"</button>
<button on:click={() => setLanguageTag("en")}>change language to "en"</button>
