// inlang/source-code/paraglide/paraglide-js-adapter-next/example-app/src/app/about/page.tsx
import { Link } from "@inlang/paraglide-js-adapter-next"
import * as m from "@/paraglide/messages.js"
import { ClientComponent } from "../ClientComponent"

export default function About() {
	return (
		<>
			<main>
				<p>{m.about()}</p>
				<Link href="/">Home</Link>
				<ClientComponent />
			</main>
		</>
	)
}

// packages/paraglide/paraglide-js-adapter-solidstart/example/src/routes/about.tsx
import { Component } from "solid-js"
import { A } from "solid-start"
import * as m from "../paraglide/messages.js"
import { LocaleSwitcher, translateHref } from "../i18n/index.jsx"

const About: Component = () => {
	return (
		<main>
			<h1>{m.about()}</h1>

			<A href={translateHref("/")}>{m.home()}</A>
			<br />
			<LocaleSwitcher />
		</main>
	)
}
export default About
