// inlang/source-code/paraglide/paraglide-js-adapter-next/examples/app/src/lib/ui/Header.tsx
"use client"
import * as m from "@/paraglide/messages.js"
import { Link } from "@/lib/i18n"
import { SelectLanguage } from "./SelectLanguage"
import { usePathname } from "next/navigation"

export function Header() {
	const nextPathname = usePathname()

	return (
		<header
			style={{
				display: "flex",
				justifyContent: "space-between",
				alignItems: "center",
				padding: "1rem",
				borderBottom: "1px solid #ccc",
			}}
		>
			<nav
				style={{
					display: "flex",
					gap: "1rem",
				}}
			>
				<Link href="/">{m.home()}</Link>
				<Link href="/about">{m.about()}</Link>
			</nav>
			<div>{nextPathname}</div>

			<SelectLanguage />
		</header>
	)
}

// inlang/source-code/paraglide/paraglide-sveltekit/example/src/lib/ui/Header.svelte
<script>
	import LanguageSwitcher from "./LanguageSwitcher.svelte"
    import { page } from "$app/stores";
    import * as m from "$lib/paraglide/messages.js"
</script>
<header>
    <nav>
        <a href="/" aria-current={$page.route.id === "/" ? "page" : undefined}>{m.home()}</a>
        <a href="/about/" aria-current={$page.route.id === "/about" ? "page" : undefined}>{m.about()}</a>
        <a href="/users/1" aria-current={$page.route.id === "/users/[id]" ? "page" : undefined}>{m.users()}</a>
    </nav>
    <span>{$page.url.pathname}</span>
    <LanguageSwitcher />
</header>


<style>
    header {
        display: flex;
        padding: 1em;
        justify-content: space-between;
        border-bottom: 1px solid #e0e0e0;
    }

    nav {
        display: flex;
        gap : 1em;
    }

    a[aria-current="page"] {
        font-weight: bold;
    }
</style>
